In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("../input/easemytrip-flight-fare-travel-listings/marketing_sample_for_easemytrip_in-easemytrip_flights_fares__20200401_20200630__30k_data.csv")
df

,Uniq Id,Crawl Timestamp,Source,Layover1,Layover2,Layover3,Destination,Flight Operator,Flight Number,Departure Date,Departure Time,Arrival Date,Arrival Time,Total Time,Number Of Stops,Fare
0,53f192419756cfa95baa4745067354f5,2020-04-01 01:23:42 +0000,Delhi,Patna,NaN,NaN,Guwahati,SpiceJet|SpiceJet,SG-8751|SG-426,23Apr2020,13:10,23Apr2020,22:00,08h 50m,1,4378.0
1,7bb845050e88cc6a4f17abf24794c73b,2020-04-01 00:59:51 +0000,Mumbai,Bangalore,Delhi,NaN,Kochi,Vistara|Vistara|Vistara,UK-851|UK-812|UK-885,18Apr2020,07:00,18Apr2020,19:10,12h 10m,2,7465.0
2,c9a84cc24d8a350eb41555c7bb76def6,2020-04-01 00:56:35 +0000,Ahmedabad,Delhi,Kolkata,NaN,Guwahati,Air India|Air India|Air India,AI-18|AI-401|AI-729,25Apr2020,07:10,26Apr2020,11:05,27h 55m,2,6179.0
3,0c0a87ac2229b8c3f1b322baf1fc9f4e,2020-04-01 00:42:35 +0000,Kolkata,Delhi,NaN,NaN,Kochi,SpiceJet|SpiceJet,SG-254|SG-8561,16Apr2020,18:00,17Apr2020,11:10,17h 10m,1,5226.0
4,b8f8af12fd6d9bf2f24389f26488478c,2020-04-01 01:52:13 +0000,Indore,Mumbai,NaN,NaN,Chennai,Indigo|Indigo,6E-5321|6E-323,18Apr2020,07:25,18Apr2020,13:35,06h 10m,1,3333.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,35c0bbbb50478edb124b6987ae54864a,2020-04-01 01:50:52 +0000,Ranchi,Delhi,NaN,NaN,Chennai,Indigo|Indigo,6E-436|6E-2162,18Apr2020,14:50,18Apr2020,23:35,08h 45m,1,4161.0
29996,80c354a117f6abea283fd44dd25a95d6,2020-04-01 01:11:27 +0000,Ahmedabad,Pune,NaN,NaN,Bengaluru,SpiceJet|SpiceJet,SG-6630|SG-517,16Apr2020,04:00,16Apr2020,17:05,13h 05m,1,2145.0
29997,e26c8fd1922e77256b458da1c5895074,2020-04-01 00:57:21 +0000,Mumbai,Delhi,NaN,NaN,Ranchi,Vistara|Vistara,UK-970|UK-751,18Apr2020,08:45,19Apr2020,09:55,25h 10m,1,5009.0
29998,6a81ee6ea557a970dab4499550f27a6c,2020-04-01 01:46:12 +0000,Bhopal,Raipur,Mumbai,NaN,Shirdi,Air India|Air India|Air India,AI-9683|AI-651|AI-9653,16Apr2020,07:50,17Apr2020,16:10,32h 20m,2,11378.0
29999,29610e1ac73f6b2bbf2827ba3d8f8f33,2020-04-01 01:14:48 +0000,Delhi,NaN,NaN,NaN,Hyderabad,GoAir,G8-422,18Apr2020,20:55,18Apr2020,23:10,02h 15m,0,2351.0

In [3]:
df.columns

Index(['Uniq Id', 'Crawl Timestamp', 'Source', 'Layover1', 'Layover2',
       'Layover3', 'Destination', 'Flight Operator', 'Flight Number',
       'Departure Date', 'Departure Time', 'Arrival Date', 'Arrival Time',
       'Total Time', 'Number Of Stops', 'Fare'],
      dtype='object')

In [4]:
df=df.drop(['Uniq Id','Flight Number'],axis=1)

In [5]:
df.columns

Index(['Crawl Timestamp', 'Source', 'Layover1', 'Layover2', 'Layover3',
       'Destination', 'Flight Operator', 'Departure Date', 'Departure Time',
       'Arrival Date', 'Arrival Time', 'Total Time', 'Number Of Stops',
       'Fare'],
      dtype='object')

In [6]:
df[df['Number Of Stops']==1].shape

(16238, 14)

In [7]:
df1=df[np.logical_or(df['Number Of Stops']==1 , df['Number Of Stops']==0)]

In [8]:
df1

,Crawl Timestamp,Source,Layover1,Layover2,Layover3,Destination,Flight Operator,Departure Date,Departure Time,Arrival Date,Arrival Time,Total Time,Number Of Stops,Fare
0,2020-04-01 01:23:42 +0000,Delhi,Patna,NaN,NaN,Guwahati,SpiceJet|SpiceJet,23Apr2020,13:10,23Apr2020,22:00,08h 50m,1,4378.0
3,2020-04-01 00:42:35 +0000,Kolkata,Delhi,NaN,NaN,Kochi,SpiceJet|SpiceJet,16Apr2020,18:00,17Apr2020,11:10,17h 10m,1,5226.0
4,2020-04-01 01:52:13 +0000,Indore,Mumbai,NaN,NaN,Chennai,Indigo|Indigo,18Apr2020,07:25,18Apr2020,13:35,06h 10m,1,3333.0
7,2020-04-01 01:20:18 +0000,Kochi,Mumbai,NaN,NaN,Delhi,SpiceJet|SpiceJet,27Apr2020,05:35,27Apr2020,15:40,10h 05m,1,3563.0
8,2020-04-01 01:10:52 +0000,Vadodara,Delhi,NaN,NaN,Mumbai,Air India|Air India,18Apr2020,20:20,19Apr2020,12:50,16h 30m,1,5309.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,2020-04-01 02:16:24 +0000,Abudhabi,Colombo,NaN,NaN,Chennai,SriLankan Airlines|SriLankan Airlines,23Apr2020,23:00,24Apr2020,08:50,08h 20m,1,35839.0
29995,2020-04-01 01:50:52 +0000,Ranchi,Delhi,NaN,NaN,Chennai,Indigo|Indigo,18Apr2020,14:50,18Apr2020,23:35,08h 45m,1,4161.0
29996,2020-04-01 01:11:27 +0000,Ahmedabad,Pune,NaN,NaN,Bengaluru,SpiceJet|SpiceJet,16Apr2020,04:00,16Apr2020,17:05,13h 05m,1,2145.0
29997,2020-04-01 00:57:21 +0000,Mumbai,Delhi,NaN,NaN,Ranchi,Vistara|Vistara,18Apr2020,08:45,19Apr2020,09:55,25h 10m,1,5009.0
29999,2020-04-01 01:14:48 +0000,Delhi,NaN,NaN,NaN,Hyderabad,GoAir,18Apr2020,20:55,18Apr2020,23:10,02h 15m,0,2351.0

In [9]:
df1['Flight Operator'].unique()

array(['SpiceJet|SpiceJet', 'Indigo|Indigo', 'Air India|Air India',
       'GoAir', 'British Airways|British Airways', 'AirAsia', 'Indigo',
       'Vistara|Vistara', 'AirAsia|AirAsia', 'GoAir|GoAir',
       'Etihad Airways|Etihad Airways',
       'National Air Services|National Air Services', 'SpiceJet',
       'Qatar Airways|Qatar Airways', 'AirArabia|AirArabia', 'Vistara',
       'Lufthansa Airways|Air India', 'Virgin Atlantic Airways|Air India',
       'Turkish Airlines|Turkish Airlines',
       'LOT Polish Airlines|LOT Polish Airlines',
       'SriLankan Airlines|SriLankan Airlines', 'Air India',
       'Nepal Airways', 'Gulf Airways|Gulf Airways',
       'Ethiopian Airlines|Ethiopian Airlines',
       'Saudi Arabian Airlines|Saudi Arabian Airlines', 'Etihad Airways',
       'EVA Airways|China Eastern Airlines', 'SriLankan Airlines',
       'Virgin Atlantic Airways|Virgin Atlantic Airways', 'Trujet',
       'Saudi Arabian Airlines', 'Delta Airlines|Delta Airlines',
       'American Airlines|American Airlines',
       'Lufthansa Airways|Etihad Airways', 'Gulf Airways|Air India',
       'Virgin Atlantic Airways|Vistara',
       'Malaysia Airlines|SriLankan Airlines',
       'Lufthansa Airways|LOT Polish Airlines',
       'Iberia Airlines|Air India', 'Sichuan Airlines|Air India',
       'Hong Kong Airlines|All Nippon Airways',
       'All Nippon Airways|All Nippon Airways', 'Alitalia|Air India',
       'Malaysia Airlines|Air India', 'Kenya Airways|Kenya Airways',
       'Singapore Airlines|Singapore Airlines', 'Rwandair|Air India',
       'Biman Bangladesh|Biman Bangladesh', 'All Nippon Airways|Vistara',
       'Ethiopian Airlines|Air India', 'Cathay Pacific Airways|Air India',
       'Thai Airways International|All Nippon Airways',
       'British Airways|Air India', 'Scandinavian Airlines|Air India',
       'Shanghai Airlines|Cathay Pacific Airways', 'Air India Express',
       'United Airlines|Air India', 'National Air Services',
       'Lufthansa Airways|British Airways', 'FlyDubai',
       'Shanghai Airlines|China Eastern Airlines',
       'Saudi Arabian Airlines|Air India',
       'Ukraine Intl Airlines|Ukraine Intl Airlines', 'Gulf Airways',
       'AirArabia', 'Gulf Airways|Etihad Airways',
       'Biman Bangladesh|Vistara',
       'Cathay Pacific Airways|All Nippon Airways',
       'Turkish Airlines|Air India', 'China Eastern Airlines|Air India',
       'All Nippon Airways|Air Pacific', 'British Airways|Vistara',
       'Air Canada|Air India', 'Alitalia|Virgin Atlantic Airways',
       'Swiss|Air India', 'Etihad Airways|Air India',
       'American Airlines|British Airways', 'Jetstar Asia|Air India',
       'Virgin Atlantic Airways', 'Singapore Airlines|Air India',
       'Austrian Airways|Air India', 'Oman Air|Qatar Airways',
       'Nepal Airways|Nepal Airways', 'Oman Air|Oman Air',
       'Lufthansa Airways|Lufthansa Airways', 'Ethiopian Airlines',
       'KLM Airlines|Virgin Atlantic Airways',
       'All Nippon Airways|Air India', 'Biman Bangladesh',
       'British Airways', 'Air France|British Airways',
       'Etihad Airways|SriLankan Airlines',
       'Scandinavian Airlines|Virgin Atlantic Airways',
       'China Eastern Airlines|China Eastern Airlines',
       'All Nippon Airways', 'EVA Airways|Cathay Pacific Airways',
       'Hong Kong Airlines|Cathay Pacific Airways',
       'Air Canada|Air Canada', 'SriLankan Airlines|Air India',
       'Turkish Airlines', 'Korean Airways|All Nippon Airways',
       'Lufthansa Airways|Virgin Atlantic Airways',
       'China Southern Airlines|China Eastern Airlines',
       'Air India Express|Air India Express', 'Swiss|British Airways',
       'Air France|Air India', 'Trujet|Trujet',
       'Ethiopian Airlines|Vistara', 'Korean Airways|Etihad Airways',
       'SriLankan Airlines|Biman Bangladesh', 'Jetstar Airways|Air India',
       'Oman Air', 'Qantas Airways|Air India',
       'Brussels Airlines|Air India', 'China Airlines|Air India',
       'Kenya Airways|Air India', 'Dragonair|Cathay Pacific Airways',
       'Oman Air|Air India', 'Singapore Airlines|Vistara',
       'Jazeera Airways', 'Deutsche Bahn Ag|Air India',
       'Myanmar Airways Intl', 'Kenya Airways',
       'Silk Air|Singapore Airlines', 'Etihad Airways|British Airways',
       'China Southern Airlines|Etihad Airways',
       'Austrian Airways|LOT Polish Airlines'], dtype=object)

In [10]:
df1['Flight Operator']=df1['Flight Operator']+'|'
val=df1['Flight Operator'].str.split("|")

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [11]:
val

0                            [SpiceJet, SpiceJet, ]
3                            [SpiceJet, SpiceJet, ]
4                                [Indigo, Indigo, ]
7                            [SpiceJet, SpiceJet, ]
8                          [Air India, Air India, ]
                            ...
29994    [SriLankan Airlines, SriLankan Airlines, ]
29995                            [Indigo, Indigo, ]
29996                        [SpiceJet, SpiceJet, ]
29997                          [Vistara, Vistara, ]
29999                                     [GoAir, ]
Name: Flight Operator, Length: 17848, dtype: object

In [12]:
v1=[]
v2=[]
for i in val:
    v1.append(i[0])
    v2.append(i[1])

In [13]:
df1['F1']=v1
df1['F2']=v2

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
df1.columns

Index(['Crawl Timestamp', 'Source', 'Layover1', 'Layover2', 'Layover3',
       'Destination', 'Flight Operator', 'Departure Date', 'Departure Time',
       'Arrival Date', 'Arrival Time', 'Total Time', 'Number Of Stops', 'Fare',
       'F1', 'F2'],
      dtype='object')

In [15]:
df1.shape

(17848, 16)

In [16]:
df1=df1[np.logical_or(df1['Number Of Stops']==0,np.logical_and(df1['Number Of Stops']==1,df1['F1']==df1['F2']))]

In [17]:
df1

,Crawl Timestamp,Source,Layover1,Layover2,Layover3,Destination,Flight Operator,Departure Date,Departure Time,Arrival Date,Arrival Time,Total Time,Number Of Stops,Fare,F1,F2
0,2020-04-01 01:23:42 +0000,Delhi,Patna,NaN,NaN,Guwahati,SpiceJet|SpiceJet|,23Apr2020,13:10,23Apr2020,22:00,08h 50m,1,4378.0,SpiceJet,SpiceJet
3,2020-04-01 00:42:35 +0000,Kolkata,Delhi,NaN,NaN,Kochi,SpiceJet|SpiceJet|,16Apr2020,18:00,17Apr2020,11:10,17h 10m,1,5226.0,SpiceJet,SpiceJet
4,2020-04-01 01:52:13 +0000,Indore,Mumbai,NaN,NaN,Chennai,Indigo|Indigo|,18Apr2020,07:25,18Apr2020,13:35,06h 10m,1,3333.0,Indigo,Indigo
7,2020-04-01 01:20:18 +0000,Kochi,Mumbai,NaN,NaN,Delhi,SpiceJet|SpiceJet|,27Apr2020,05:35,27Apr2020,15:40,10h 05m,1,3563.0,SpiceJet,SpiceJet
8,2020-04-01 01:10:52 +0000,Vadodara,Delhi,NaN,NaN,Mumbai,Air India|Air India|,18Apr2020,20:20,19Apr2020,12:50,16h 30m,1,5309.0,Air India,Air India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,2020-04-01 02:16:24 +0000,Abudhabi,Colombo,NaN,NaN,Chennai,SriLankan Airlines|SriLankan Airlines|,23Apr2020,23:00,24Apr2020,08:50,08h 20m,1,35839.0,SriLankan Airlines,SriLankan Airlines
29995,2020-04-01 01:50:52 +0000,Ranchi,Delhi,NaN,NaN,Chennai,Indigo|Indigo|,18Apr2020,14:50,18Apr2020,23:35,08h 45m,1,4161.0,Indigo,Indigo
29996,2020-04-01 01:11:27 +0000,Ahmedabad,Pune,NaN,NaN,Bengaluru,SpiceJet|SpiceJet|,16Apr2020,04:00,16Apr2020,17:05,13h 05m,1,2145.0,SpiceJet,SpiceJet
29997,2020-04-01 00:57:21 +0000,Mumbai,Delhi,NaN,NaN,Ranchi,Vistara|Vistara|,18Apr2020,08:45,19Apr2020,09:55,25h 10m,1,5009.0,Vistara,Vistara
29999,2020-04-01 01:14:48 +0000,Delhi,NaN,NaN,NaN,Hyderabad,GoAir|,18Apr2020,20:55,18Apr2020,23:10,02h 15m,0,2351.0,GoAir,

In [18]:
df1['F1'].unique()

array(['SpiceJet', 'Indigo', 'Air India', 'GoAir', 'British Airways',
       'AirAsia', 'Vistara', 'Etihad Airways', 'National Air Services',
       'Qatar Airways', 'AirArabia', 'Turkish Airlines',
       'LOT Polish Airlines', 'SriLankan Airlines', 'Nepal Airways',
       'Gulf Airways', 'Ethiopian Airlines', 'Saudi Arabian Airlines',
       'Virgin Atlantic Airways', 'Trujet', 'Delta Airlines',
       'American Airlines', 'All Nippon Airways', 'Kenya Airways',
       'Singapore Airlines', 'Biman Bangladesh', 'Air India Express',
       'FlyDubai', 'Ukraine Intl Airlines', 'Oman Air',
       'Lufthansa Airways', 'China Eastern Airlines', 'Air Canada',
       'Jazeera Airways', 'Myanmar Airways Intl'], dtype=object)

In [19]:
df1=df1.drop(['Layover2', 'Layover3','Flight Operator','F2'],axis=1)

In [20]:
df1

,Crawl Timestamp,Source,Layover1,Destination,Departure Date,Departure Time,Arrival Date,Arrival Time,Total Time,Number Of Stops,Fare,F1
0,2020-04-01 01:23:42 +0000,Delhi,Patna,Guwahati,23Apr2020,13:10,23Apr2020,22:00,08h 50m,1,4378.0,SpiceJet
3,2020-04-01 00:42:35 +0000,Kolkata,Delhi,Kochi,16Apr2020,18:00,17Apr2020,11:10,17h 10m,1,5226.0,SpiceJet
4,2020-04-01 01:52:13 +0000,Indore,Mumbai,Chennai,18Apr2020,07:25,18Apr2020,13:35,06h 10m,1,3333.0,Indigo
7,2020-04-01 01:20:18 +0000,Kochi,Mumbai,Delhi,27Apr2020,05:35,27Apr2020,15:40,10h 05m,1,3563.0,SpiceJet
8,2020-04-01 01:10:52 +0000,Vadodara,Delhi,Mumbai,18Apr2020,20:20,19Apr2020,12:50,16h 30m,1,5309.0,Air India
...,...,...,...,...,...,...,...,...,...,...,...,...
29994,2020-04-01 02:16:24 +0000,Abudhabi,Colombo,Chennai,23Apr2020,23:00,24Apr2020,08:50,08h 20m,1,35839.0,SriLankan Airlines
29995,2020-04-01 01:50:52 +0000,Ranchi,Delhi,Chennai,18Apr2020,14:50,18Apr2020,23:35,08h 45m,1,4161.0,Indigo
29996,2020-04-01 01:11:27 +0000,Ahmedabad,Pune,Bengaluru,16Apr2020,04:00,16Apr2020,17:05,13h 05m,1,2145.0,SpiceJet
29997,2020-04-01 00:57:21 +0000,Mumbai,Delhi,Ranchi,18Apr2020,08:45,19Apr2020,09:55,25h 10m,1,5009.0,Vistara
29999,2020-04-01 01:14:48 +0000,Delhi,NaN,Hyderabad,18Apr2020,20:55,18Apr2020,23:10,02h 15m,0,2351.0,GoAir

In [21]:
df1.dtypes

Crawl Timestamp     object
Source              object
Layover1            object
Destination         object
Departure Date      object
Departure Time      object
Arrival Date        object
Arrival Time        object
Total Time          object
Number Of Stops      int64
Fare               float64
F1                  object
dtype: object

In [22]:
from datetime import datetime

In [23]:
df1.head()

,Crawl Timestamp,Source,Layover1,Destination,Departure Date,Departure Time,Arrival Date,Arrival Time,Total Time,Number Of Stops,Fare,F1
0,2020-04-01 01:23:42 +0000,Delhi,Patna,Guwahati,23Apr2020,13:10,23Apr2020,22:00,08h 50m,1,4378.0,SpiceJet
3,2020-04-01 00:42:35 +0000,Kolkata,Delhi,Kochi,16Apr2020,18:00,17Apr2020,11:10,17h 10m,1,5226.0,SpiceJet
4,2020-04-01 01:52:13 +0000,Indore,Mumbai,Chennai,18Apr2020,07:25,18Apr2020,13:35,06h 10m,1,3333.0,Indigo
7,2020-04-01 01:20:18 +0000,Kochi,Mumbai,Delhi,27Apr2020,05:35,27Apr2020,15:40,10h 05m,1,3563.0,SpiceJet
8,2020-04-01 01:10:52 +0000,Vadodara,Delhi,Mumbai,18Apr2020,20:20,19Apr2020,12:50,16h 30m,1,5309.0,Air India

In [24]:
df1['Crawl Timestamp']=pd.to_datetime(df1['Crawl Timestamp'])

In [25]:
df1.head()

,Crawl Timestamp,Source,Layover1,Destination,Departure Date,Departure Time,Arrival Date,Arrival Time,Total Time,Number Of Stops,Fare,F1
0,2020-04-01 01:23:42+00:00,Delhi,Patna,Guwahati,23Apr2020,13:10,23Apr2020,22:00,08h 50m,1,4378.0,SpiceJet
3,2020-04-01 00:42:35+00:00,Kolkata,Delhi,Kochi,16Apr2020,18:00,17Apr2020,11:10,17h 10m,1,5226.0,SpiceJet
4,2020-04-01 01:52:13+00:00,Indore,Mumbai,Chennai,18Apr2020,07:25,18Apr2020,13:35,06h 10m,1,3333.0,Indigo
7,2020-04-01 01:20:18+00:00,Kochi,Mumbai,Delhi,27Apr2020,05:35,27Apr2020,15:40,10h 05m,1,3563.0,SpiceJet
8,2020-04-01 01:10:52+00:00,Vadodara,Delhi,Mumbai,18Apr2020,20:20,19Apr2020,12:50,16h 30m,1,5309.0,Air India

In [26]:
df1.dtypes

Crawl Timestamp    datetime64[ns, UTC]
Source                          object
Layover1                        object
Destination                     object
Departure Date                  object
Departure Time                  object
Arrival Date                    object
Arrival Time                    object
Total Time                      object
Number Of Stops                  int64
Fare                           float64
F1                              object
dtype: object

In [27]:
df1['Departure']=df1['Departure Date']+" "+df1['Departure Time']

In [28]:
df1['Departure']=pd.to_datetime(df1['Departure'])
df1.dtypes

Crawl Timestamp    datetime64[ns, UTC]
Source                          object
Layover1                        object
Destination                     object
Departure Date                  object
Departure Time                  object
Arrival Date                    object
Arrival Time                    object
Total Time                      object
Number Of Stops                  int64
Fare                           float64
F1                              object
Departure               datetime64[ns]
dtype: object

In [29]:
df1.head()

,Crawl Timestamp,Source,Layover1,Destination,Departure Date,Departure Time,Arrival Date,Arrival Time,Total Time,Number Of Stops,Fare,F1,Departure
0,2020-04-01 01:23:42+00:00,Delhi,Patna,Guwahati,23Apr2020,13:10,23Apr2020,22:00,08h 50m,1,4378.0,SpiceJet,2020-04-23 13:10:00
3,2020-04-01 00:42:35+00:00,Kolkata,Delhi,Kochi,16Apr2020,18:00,17Apr2020,11:10,17h 10m,1,5226.0,SpiceJet,2020-04-16 18:00:00
4,2020-04-01 01:52:13+00:00,Indore,Mumbai,Chennai,18Apr2020,07:25,18Apr2020,13:35,06h 10m,1,3333.0,Indigo,2020-04-18 07:25:00
7,2020-04-01 01:20:18+00:00,Kochi,Mumbai,Delhi,27Apr2020,05:35,27Apr2020,15:40,10h 05m,1,3563.0,SpiceJet,2020-04-27 05:35:00
8,2020-04-01 01:10:52+00:00,Vadodara,Delhi,Mumbai,18Apr2020,20:20,19Apr2020,12:50,16h 30m,1,5309.0,Air India,2020-04-18 20:20:00

In [30]:
df1['Crawl Timestamp']=pd.to_datetime(df1['Crawl Timestamp']).dt.tz_localize(None)

In [31]:
df1.dtypes

Crawl Timestamp    datetime64[ns]
Source                     object
Layover1                   object
Destination                object
Departure Date             object
Departure Time             object
Arrival Date               object
Arrival Time               object
Total Time                 object
Number Of Stops             int64
Fare                      float64
F1                         object
Departure          datetime64[ns]
dtype: object

In [32]:
df1

,Crawl Timestamp,Source,Layover1,Destination,Departure Date,Departure Time,Arrival Date,Arrival Time,Total Time,Number Of Stops,Fare,F1,Departure
0,2020-04-01 01:23:42,Delhi,Patna,Guwahati,23Apr2020,13:10,23Apr2020,22:00,08h 50m,1,4378.0,SpiceJet,2020-04-23 13:10:00
3,2020-04-01 00:42:35,Kolkata,Delhi,Kochi,16Apr2020,18:00,17Apr2020,11:10,17h 10m,1,5226.0,SpiceJet,2020-04-16 18:00:00
4,2020-04-01 01:52:13,Indore,Mumbai,Chennai,18Apr2020,07:25,18Apr2020,13:35,06h 10m,1,3333.0,Indigo,2020-04-18 07:25:00
7,2020-04-01 01:20:18,Kochi,Mumbai,Delhi,27Apr2020,05:35,27Apr2020,15:40,10h 05m,1,3563.0,SpiceJet,2020-04-27 05:35:00
8,2020-04-01 01:10:52,Vadodara,Delhi,Mumbai,18Apr2020,20:20,19Apr2020,12:50,16h 30m,1,5309.0,Air India,2020-04-18 20:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,2020-04-01 02:16:24,Abudhabi,Colombo,Chennai,23Apr2020,23:00,24Apr2020,08:50,08h 20m,1,35839.0,SriLankan Airlines,2020-04-23 23:00:00
29995,2020-04-01 01:50:52,Ranchi,Delhi,Chennai,18Apr2020,14:50,18Apr2020,23:35,08h 45m,1,4161.0,Indigo,2020-04-18 14:50:00
29996,2020-04-01 01:11:27,Ahmedabad,Pune,Bengaluru,16Apr2020,04:00,16Apr2020,17:05,13h 05m,1,2145.0,SpiceJet,2020-04-16 04:00:00
29997,2020-04-01 00:57:21,Mumbai,Delhi,Ranchi,18Apr2020,08:45,19Apr2020,09:55,25h 10m,1,5009.0,Vistara,2020-04-18 08:45:00
29999,2020-04-01 01:14:48,Delhi,NaN,Hyderabad,18Apr2020,20:55,18Apr2020,23:10,02h 15m,0,2351.0,GoAir,2020-04-18 20:55:00

In [33]:
delta = df1['Departure'] - df1['Crawl Timestamp']

In [34]:
delta

0       22 days 11:46:18
3       15 days 17:17:25
4       17 days 05:32:47
7       26 days 04:14:42
8       17 days 19:09:08
              ...
29994   22 days 20:43:36
29995   17 days 12:59:08
29996   15 days 02:48:33
29997   17 days 07:47:39
29999   17 days 19:40:12
Length: 17340, dtype: timedelta64[ns]

In [35]:
d=[]
for i in delta:
    d.append(i.days)

In [36]:
df1['Days Left']=d

In [37]:
df1

,Crawl Timestamp,Source,Layover1,Destination,Departure Date,Departure Time,Arrival Date,Arrival Time,Total Time,Number Of Stops,Fare,F1,Departure,Days Left
0,2020-04-01 01:23:42,Delhi,Patna,Guwahati,23Apr2020,13:10,23Apr2020,22:00,08h 50m,1,4378.0,SpiceJet,2020-04-23 13:10:00,22
3,2020-04-01 00:42:35,Kolkata,Delhi,Kochi,16Apr2020,18:00,17Apr2020,11:10,17h 10m,1,5226.0,SpiceJet,2020-04-16 18:00:00,15
4,2020-04-01 01:52:13,Indore,Mumbai,Chennai,18Apr2020,07:25,18Apr2020,13:35,06h 10m,1,3333.0,Indigo,2020-04-18 07:25:00,17
7,2020-04-01 01:20:18,Kochi,Mumbai,Delhi,27Apr2020,05:35,27Apr2020,15:40,10h 05m,1,3563.0,SpiceJet,2020-04-27 05:35:00,26
8,2020-04-01 01:10:52,Vadodara,Delhi,Mumbai,18Apr2020,20:20,19Apr2020,12:50,16h 30m,1,5309.0,Air India,2020-04-18 20:20:00,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,2020-04-01 02:16:24,Abudhabi,Colombo,Chennai,23Apr2020,23:00,24Apr2020,08:50,08h 20m,1,35839.0,SriLankan Airlines,2020-04-23 23:00:00,22
29995,2020-04-01 01:50:52,Ranchi,Delhi,Chennai,18Apr2020,14:50,18Apr2020,23:35,08h 45m,1,4161.0,Indigo,2020-04-18 14:50:00,17
29996,2020-04-01 01:11:27,Ahmedabad,Pune,Bengaluru,16Apr2020,04:00,16Apr2020,17:05,13h 05m,1,2145.0,SpiceJet,2020-04-16 04:00:00,15
29997,2020-04-01 00:57:21,Mumbai,Delhi,Ranchi,18Apr2020,08:45,19Apr2020,09:55,25h 10m,1,5009.0,Vistara,2020-04-18 08:45:00,17
29999,2020-04-01 01:14:48,Delhi,NaN,Hyderabad,18Apr2020,20:55,18Apr2020,23:10,02h 15m,0,2351.0,GoAir,2020-04-18 20:55:00,17

In [38]:
days1=[]
m1=[]
yrs=[]
hrs=[]
mins=[]
for i in df1['Departure']:
    days1.append(i.day)
    yrs.append(i.year)
    m1.append(i.month)
    hrs.append(i.hour)
    mins.append(i.minute)

In [39]:
df1["Departure_day"]=days1
df1["Departure_month"]=m1
df1["Departure_year"]=yrs
df1["Departure_hour"]=hrs
df1["Departure_minute"]=mins

In [40]:
df1

,Crawl Timestamp,Source,Layover1,Destination,Departure Date,Departure Time,Arrival Date,Arrival Time,Total Time,Number Of Stops,Fare,F1,Departure,Days Left,Departure_day,Departure_month,Departure_year,Departure_hour,Departure_minute
0,2020-04-01 01:23:42,Delhi,Patna,Guwahati,23Apr2020,13:10,23Apr2020,22:00,08h 50m,1,4378.0,SpiceJet,2020-04-23 13:10:00,22,23,4,2020,13,10
3,2020-04-01 00:42:35,Kolkata,Delhi,Kochi,16Apr2020,18:00,17Apr2020,11:10,17h 10m,1,5226.0,SpiceJet,2020-04-16 18:00:00,15,16,4,2020,18,0
4,2020-04-01 01:52:13,Indore,Mumbai,Chennai,18Apr2020,07:25,18Apr2020,13:35,06h 10m,1,3333.0,Indigo,2020-04-18 07:25:00,17,18,4,2020,7,25
7,2020-04-01 01:20:18,Kochi,Mumbai,Delhi,27Apr2020,05:35,27Apr2020,15:40,10h 05m,1,3563.0,SpiceJet,2020-04-27 05:35:00,26,27,4,2020,5,35
8,2020-04-01 01:10:52,Vadodara,Delhi,Mumbai,18Apr2020,20:20,19Apr2020,12:50,16h 30m,1,5309.0,Air India,2020-04-18 20:20:00,17,18,4,2020,20,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,2020-04-01 02:16:24,Abudhabi,Colombo,Chennai,23Apr2020,23:00,24Apr2020,08:50,08h 20m,1,35839.0,SriLankan Airlines,2020-04-23 23:00:00,22,23,4,2020,23,0
29995,2020-04-01 01:50:52,Ranchi,Delhi,Chennai,18Apr2020,14:50,18Apr2020,23:35,08h 45m,1,4161.0,Indigo,2020-04-18 14:50:00,17,18,4,2020,14,50
29996,2020-04-01 01:11:27,Ahmedabad,Pune,Bengaluru,16Apr2020,04:00,16Apr2020,17:05,13h 05m,1,2145.0,SpiceJet,2020-04-16 04:00:00,15,16,4,2020,4,0
29997,2020-04-01 00:57:21,Mumbai,Delhi,Ranchi,18Apr2020,08:45,19Apr2020,09:55,25h 10m,1,5009.0,Vistara,2020-04-18 08:45:00,17,18,4,2020,8,45
29999,2020-04-01 01:14:48,Delhi,NaN,Hyderabad,18Apr2020,20:55,18Apr2020,23:10,02h 15m,0,2351.0,GoAir,2020-04-18 20:55:00,17,18,4,2020,20,55

In [41]:
df1.columns

Index(['Crawl Timestamp', 'Source', 'Layover1', 'Destination',
       'Departure Date', 'Departure Time', 'Arrival Date', 'Arrival Time',
       'Total Time', 'Number Of Stops', 'Fare', 'F1', 'Departure', 'Days Left',
       'Departure_day', 'Departure_month', 'Departure_year', 'Departure_hour',
       'Departure_minute'],
      dtype='object')

In [42]:
df1=df1.drop(['Crawl Timestamp','Departure Date', 'Departure Time', 'Arrival Date', 'Arrival Time',
       'Total Time','Departure'],axis=1)

In [43]:
df1.columns

Index(['Source', 'Layover1', 'Destination', 'Number Of Stops', 'Fare', 'F1',
       'Days Left', 'Departure_day', 'Departure_month', 'Departure_year',
       'Departure_hour', 'Departure_minute'],
      dtype='object')

In [44]:
df1

,Source,Layover1,Destination,Number Of Stops,Fare,F1,Days Left,Departure_day,Departure_month,Departure_year,Departure_hour,Departure_minute
0,Delhi,Patna,Guwahati,1,4378.0,SpiceJet,22,23,4,2020,13,10
3,Kolkata,Delhi,Kochi,1,5226.0,SpiceJet,15,16,4,2020,18,0
4,Indore,Mumbai,Chennai,1,3333.0,Indigo,17,18,4,2020,7,25
7,Kochi,Mumbai,Delhi,1,3563.0,SpiceJet,26,27,4,2020,5,35
8,Vadodara,Delhi,Mumbai,1,5309.0,Air India,17,18,4,2020,20,20
...,...,...,...,...,...,...,...,...,...,...,...,...
29994,Abudhabi,Colombo,Chennai,1,35839.0,SriLankan Airlines,22,23,4,2020,23,0
29995,Ranchi,Delhi,Chennai,1,4161.0,Indigo,17,18,4,2020,14,50
29996,Ahmedabad,Pune,Bengaluru,1,2145.0,SpiceJet,15,16,4,2020,4,0
29997,Mumbai,Delhi,Ranchi,1,5009.0,Vistara,17,18,4,2020,8,45
29999,Delhi,NaN,Hyderabad,0,2351.0,GoAir,17,18,4,2020,20,55

In [45]:
def encode_and_bind(original_dataframe, feature_to_encode):
    dummies = pd.get_dummies(original_dataframe[[feature_to_encode]])
    res = pd.concat([original_dataframe, dummies], axis=1)
    return(res)

In [46]:
df1=encode_and_bind(df1,"F1")
df1=encode_and_bind(df1,"Source")
df1=encode_and_bind(df1,"Destination")
df1=encode_and_bind(df1,"Layover1")

In [47]:
df1

,Source,Layover1,Destination,Number Of Stops,Fare,F1,Days Left,Departure_day,Departure_month,Departure_year,...,Layover1_Tiruchirapally,Layover1_Tirupati,Layover1_Tokyo,Layover1_Udaipur,Layover1_VDY,Layover1_Vadodara,Layover1_Varanasi,Layover1_Vijayawada,Layover1_Vishakhapatnam,Layover1_Warsaw
0,Delhi,Patna,Guwahati,1,4378.0,SpiceJet,22,23,4,2020,...,0,0,0,0,0,0,0,0,0,0
3,Kolkata,Delhi,Kochi,1,5226.0,SpiceJet,15,16,4,2020,...,0,0,0,0,0,0,0,0,0,0
4,Indore,Mumbai,Chennai,1,3333.0,Indigo,17,18,4,2020,...,0,0,0,0,0,0,0,0,0,0
7,Kochi,Mumbai,Delhi,1,3563.0,SpiceJet,26,27,4,2020,...,0,0,0,0,0,0,0,0,0,0
8,Vadodara,Delhi,Mumbai,1,5309.0,Air India,17,18,4,2020,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,Abudhabi,Colombo,Chennai,1,35839.0,SriLankan Airlines,22,23,4,2020,...,0,0,0,0,0,0,0,0,0,0
29995,Ranchi,Delhi,Chennai,1,4161.0,Indigo,17,18,4,2020,...,0,0,0,0,0,0,0,0,0,0
29996,Ahmedabad,Pune,Bengaluru,1,2145.0,SpiceJet,15,16,4,2020,...,0,0,0,0,0,0,0,0,0,0
29997,Mumbai,Delhi,Ranchi,1,5009.0,Vistara,17,18,4,2020,...,0,0,0,0,0,0,0,0,0,0
29999,Delhi,NaN,Hyderabad,0,2351.0,GoAir,17,18,4,2020,...,0,0,0,0,0,0,0,0,0,0

In [48]:
df1.to_csv("EaseMyTrip-discriptive.csv")

In [49]:
df1=df1.drop(['Source', 'Layover1', 'Destination','F1'],axis=1)

In [50]:
df1

,Number Of Stops,Fare,Days Left,Departure_day,Departure_month,Departure_year,Departure_hour,Departure_minute,F1_Air Canada,F1_Air India,...,Layover1_Tiruchirapally,Layover1_Tirupati,Layover1_Tokyo,Layover1_Udaipur,Layover1_VDY,Layover1_Vadodara,Layover1_Varanasi,Layover1_Vijayawada,Layover1_Vishakhapatnam,Layover1_Warsaw
0,1,4378.0,22,23,4,2020,13,10,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,5226.0,15,16,4,2020,18,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,3333.0,17,18,4,2020,7,25,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1,3563.0,26,27,4,2020,5,35,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1,5309.0,17,18,4,2020,20,20,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,1,35839.0,22,23,4,2020,23,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29995,1,4161.0,17,18,4,2020,14,50,0,0,...,0,0,0,0,0,0,0,0,0,0
29996,1,2145.0,15,16,4,2020,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29997,1,5009.0,17,18,4,2020,8,45,0,0,...,0,0,0,0,0,0,0,0,0,0
29999,0,2351.0,17,18,4,2020,20,55,0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
df1.dtypes

Number Of Stops              int64
Fare                       float64
Days Left                    int64
Departure_day                int64
Departure_month              int64
                            ...
Layover1_Vadodara            uint8
Layover1_Varanasi            uint8
Layover1_Vijayawada          uint8
Layover1_Vishakhapatnam      uint8
Layover1_Warsaw              uint8
Length: 365, dtype: object

In [52]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17340 entries, 0 to 29999
Columns: 365 entries, Number Of Stops to Layover1_Warsaw
dtypes: float64(1), int64(7), uint8(357)
memory usage: 7.1 MB

In [53]:
df1.isnull().values.any()

False

In [54]:
df1.to_csv("EaseMyTrip.csv")